let nameMap = {
  "charactor/Ganyu": "cardface/Char_Avatar_Ganyu.png",
  "charactor/Kaeya": "cardface/Char_Avatar_Kaeya.png",
  "charactor/Chongyun": "cardface/Char_Avatar_Chongyun.png",
  "charactor/Shenhe": "cardface/Char_Avatar_Shenhe.png",
  "charactor/Barbara": "cardface/Char_Avatar_Barbara.png",
  "charactor/Xingqiu": "cardface/Char_Avatar_Xingqiu.png",
  "charactor/Tartaglia": "cardface/Char_Avatar_Tartaglia.png",
  "charactor/Candace": "cardface/Char_Avatar_Candace.png",
  "charactor/Mirror Maiden": "cardface/Char_Monster_Maidenwater.png",
  "charactor/Diluc": "cardface/Char_Avatar_Diluc.png",
  "charactor/Xiangling": "cardface/Char_Avatar_Xiangling.png",
  "charactor/Bennett": "cardface/Char_Avatar_Bennett.png",
  "charactor/Yoimiya": "cardface/Char_Avatar_Yoimiya.png",
  "charactor/Hu Tao": "cardface/Char_Avatar_Hutao.png",
  "charactor/Yanfei": "cardface/Char_Avatar_Feiyan.png",
  "charactor/Dehya": "cardface/Char_Avatar_Dehya.png",
  "charactor/Fischl": "cardface/Char_Avatar_Fischl.png",
  "charactor/Razor": "cardface/Char_Avatar_Razor.png",
  "charactor/Keqing": "cardface/Char_Avatar_Keqing.png",
  "charactor/Beidou": "cardface/Char_Avatar_Beidou.png",
  "charactor/Sucrose": "cardface/Char_Avatar_Sucrose.png",
  "charactor/Venti": "cardface/Char_Avatar_Venti.png",
  "charactor/Kaedehara Kazuha": "cardface/Char_Avatar_Kazuha.png",
  "charactor/Wanderer": "cardface/Char_Avatar_Wanderer.png",
  "charactor/Ningguang": "cardface/Char_Avatar_Ningguang.png",
  "charactor/Zhongli": "cardface/Char_Avatar_Zhongli.png",
  "charactor/Albedo": "cardface/Char_Avatar_Albedo.png",
  "charactor/Collei": "cardface/Char_Avatar_Collei.png",
  "charactor/Tighnari": "cardface/Char_Avatar_Tighnari.png",
  "charactor/Nahida": "cardface/Char_Avatar_Nahida.png",
  "charactor/Yaoyao": "cardface/Char_Avatar_Yaoyao.png",
  "charactor_status/Stealth": "",
  "charactor_status/Explosive Spark": "",
  "charactor_status/Niwabi Enshou": "",
  "charactor_status/Scarlet Seal": "",
  "charactor_status/Paramita Papilio": "",
  "charactor_status/Blood Blossom": "",
  "charactor_status/Pyro Elemental Infusion": "",
  "charactor_status/Fiery Rebirth": "",
  "charactor_status/Aegis of Abyssal Flame": "",
  "charactor_status/Incineration Drive": "",
  "charactor_status/Vijnana Suffusion": "",
  "charactor_status/Superlative Superstrength": "",
  "charactor_status/Stonehide": "",
  "charactor_status/Electro Elemental Infusion": "",
  "charactor_status/Rock-Paper-Scissors Combo: Scissors": "",
  "charactor_status/Rock-Paper-Scissors Combo: Paper": "",
  "charactor_status/Electro Crystal Core": "",
  "charactor_status/The Shrine's Sacred Shade": "",
  "charactor_status/Tidecaller: Surf Embrace": "",
  "charactor_status/Crowfeather Cover": "",
  "charactor_status/Conductive": "",
  "charactor_status/Midare Ranzan: New": "",
  "charactor_status/Midare Ranzan": "",
  "charactor_status/Midare Ranzan: Pyro": "",
  "charactor_status/Midare Ranzan: Hydro": "",
  "charactor_status/Midare Ranzan: Cryo": "",
  "charactor_status/Midare Ranzan: Electro": "",
  "charactor_status/Windfavored": "",
  "charactor_status/Heron Shield": "",
  "charactor_status/Refraction": "",
  "charactor_status/Takimeguri Kanka": "",
  "charactor_status/Grimheart": "",
  "charactor_status/Cryo Elemental Infusion": "",
  "charactor_status/Frozen": "",
  "charactor_status/Satiated": "",
  "charactor_status/Jueyun Guoba": "",
  "charactor_status/Adeptus' Temptation": "",
  "charactor_status/Lotus Flower Crisp": "",
  "charactor_status/Northern Smoked Chicken": "",
  "charactor_status/Mushroom Pizza": "",
  "charactor_status/Minty Meat Rolls": "",
  "charactor_status/Sashimi Platter": "",
  "charactor_status/Tandoori Roast Chicken": "",
  "charactor_status/Butter Crab": "",
  "charactor_status/Unmovable Mountain": "",
  "charactor_status/Vermillion Hereafter": "",
  "charactor_status/Lithic Spear": "",
  "charactor_status/King's Squire": "",
  "charactor_status/Moonpiercer": "",
  "charactor_status/Heavy Strike": "",
  "charactor_status/Elemental Resonance: Shattering Ice": "",
  "charactor_status/Elemental Resonance: Fervent Flames": "",
  "team_status/Crystallize": "",
  "team_status/Rain Sword": "",
  "team_status/Floral Sidewinder": "",
  "team_status/Full Plate": "",
  "team_status/Jade Screen": "",
  "team_status/Jade Shield": "",
  "team_status/Stormzone": "",
  "team_status/Winds of Harmony": "",
  "team_status/Poetics of Fuubutsu: Pyro": "",
  "team_status/Poetics of Fuubutsu: Hydro": "",
  "team_status/Poetics of Fuubutsu: Electro": "",
  "team_status/Poetics of Fuubutsu: Cryo": "",
  "team_status/Icy Quill": "",
  "team_status/Chonghua's Frost Field": "",
  "team_status/Ice Lotus": "",
  "team_status/Cat-Claw Shield": "",
  "team_status/Flowing Cicin Shield": "",
  "team_status/Fresh Wind of Freedom": "",
  "team_status/Changing Shifts": "",
  "team_status/I Haven't Lost Yet!": "",
  "team_status/Leave It to Me!": "",
  "team_status/Elemental Resonance: Enduring Rock": "",
  "team_status/Where Is the Unseen Razor?": "",
  "team_status/Elemental Resonance: Sprawling Greenery": "",
  "team_status/Revive on cooldown": "",
  "team_status/Stone and Contracts": "",
  "team_status/Ancient Courtyard": "",
  "team_status/Rhythm of the Great Dream": "",
  "team_status/When the Crane Returned": "",
  "team_status/Wind and Freedom": "",
  "team_status/Pankration!": "",
  "team_status/Rebellious Shield": "",
  "team_status/Millennial Movement: Farewell Song": "",
  "charactor/AnemoMobMage": "cardface/custom/Anemo Mob Mage.png",
  "charactor/DendroMobMage": "cardface/custom/Dendro Mob Mage.png",
  "charactor/GeoMobMage": "cardface/custom/Geo Mob Mage.png",
  "charactor/ElectroMobMage": "cardface/custom/Electro Mob Mage.png",
  "charactor/PyroMobMage": "cardface/custom/Pyro Mob Mage.png",
  "charactor/HydroMobMage": "cardface/custom/Hydro Mob Mage.png",
  "charactor/CryoMobMage": "cardface/custom/Cryo Mob Mage.png",
  "charactor/PhysicalMob": "cardface/custom/Physical Mob.png",
  "charactor/AnemoMob": "cardface/custom/Anemo Mob.png",
  "charactor/DendroMob": "cardface/custom/Dendro Mob.png",
  "charactor/GeoMob": "cardface/custom/Geo Mob.png",
  "charactor/ElectroMob": "cardface/custom/Electro Mob.png",
  "charactor/PyroMob": "cardface/custom/Pyro Mob.png",
  "charactor/HydroMob": "cardface/custom/Hydro Mob.png",
  "charactor/CryoMob": "cardface/custom/Cryo Mob.png",
  "charactor/Jadeplume Terrorshroom": "cardface/Char_Monster_Fungusgrass.png",
  "charactor/Stonehide Lawachurl": "cardface/Char_Monster_Bruterock.png",
  "charactor/Arataki Itto": "cardface/Char_Avatar_Itto.png",
  "charactor/Noelle": "cardface/Char_Avatar_Noel.png",
  "charactor/Maguu Kenki": "cardface/Char_Monster_Ningyo.png",
  "charactor/Xiao": "cardface/Char_Avatar_Xiao.png",
  "charactor/Jean": "cardface/Char_Avatar_Qin.png",
  "charactor/Electro Hypostasis": "cardface/Char_Monster_Effigyelectric.png",
  "charactor/Lisa": "cardface/Char_Avatar_Lisa.png",
  "charactor/Yae Miko": "cardface/Char_Avatar_Yae.png",
  "charactor/Raiden Shogun": "cardface/Char_Avatar_Shougun.png",
  "charactor/Kujou Sara": "cardface/Char_Avatar_Sara.png",
  "charactor/Cyno": "cardface/Char_Avatar_Cyno.png",
  "charactor/Abyss Lector: Fathomless Flames": "cardface/Char_Monster_DeaconFire.png",
  "charactor/Fatui Pyro Agent": "cardface/Char_Monster_Fatuus.png",
  "charactor/Klee": "cardface/Char_Avatar_Klee.png",
  "charactor/Amber": "cardface/Char_Avatar_Ambor.png",
  "charactor/Rhodeia of Loch": "cardface/Char_Monster_Oceanid.png",
  "charactor/Kamisato Ayato": "cardface/Char_Avatar_Ayato.png",
  "charactor/Sangonomiya Kokomi": "cardface/Char_Avatar_Kokomi.png",
  "charactor/Mona": "cardface/Char_Avatar_Mona.png",
  "charactor/Fatui Cryo Cicin Mage": "cardface/Char_Monster_FatuusMageice.png",
  "charactor/Qiqi": "cardface/Char_Avatar_Qiqi.png",
  "charactor/Eula": "cardface/Char_Avatar_Eula.png",
  "charactor/Kamisato Ayaka": "cardface/Char_Avatar_Ayaka.png",
  "charactor/Diona": "cardface/Char_Avatar_Diona.png",
  "summon/Yuegui: Throwing Mode": "cardface/Summon_Yaoyao.png",
  "summon/Clusterbloom Arrow": "cardface/Summon_Tighnari.png",
  "summon/Cuilein-Anbar": "cardface/Summon_Collei.png",
  "summon/Ushi": "cardface/Summon_Itto.png",
  "summon/Solar Isotoma": "cardface/Summon_Albedo.png",
  "summon/Stone Stele": "cardface/Summon_Zhongli.png",
  "summon/Shadowsword: Lone Gale": "cardface/Summon_Jifengcanying.png",
  "summon/Shadowsword: Galloping Frost": "cardface/Summon_Bingshuangcanying.png",
  "summon/Autumn Whirlwind": "cardface/Summon_Kazuha.png",
  "summon/Stormeye": "cardface/Summon_Venti.png",
  "summon/Chains of Warding Thunder": "cardface/Summon_Effigyelectric.png",
  "summon/Lightning Rose": "cardface/Summon_Lisa.png",
  "summon/Sesshou Sakura": "cardface/Summon_Yae.png",
  "summon/Eye of Stormy Judgment": "cardface/Summon_Shougun.png",
  "summon/Tengu Juurai: Stormcluster": "cardface/Summon_SaraB.png",
  "summon/Tengu Juurai: Ambush": "cardface/Summon_SaraA.png",
  "summon/Oz": "cardface/Summon_Crow.png",
  "summon/Darkfire Furnace": "cardface/Summon_DeaconFire.png",
  "summon/Fiery Sanctum Field": "cardface/Summon_Dehya.png",
  "summon/Baron Bunny": "cardface/Summon_Ambor.png",
  "summon/Oceanic Mimic: Squirrel": "cardface/Summon_Ferret.png",
  "summon/Oceanic Mimic: Frog": "cardface/Summon_Frog.png",
  "summon/Garden of Purity": "cardface/Summon_Ayato.png",
  "summon/Bake-Kurage": "cardface/Summon_Kokomi.png",
  "summon/Reflection": "cardface/Summon_Mona.png",
  "summon/Melody Loop": "cardface/Summon_ShiningMiracle.png",
  "summon/Cryo Cicins": "cardface/Summon_MageIce.png",
  "summon/Herald of Frost": "cardface/Summon_Qiqi.png",
  "summon/Lightfall Sword": "cardface/Summon_Eula.png",
  "summon/Frostflake Seki no To": "cardface/Summon_KamisatoRyu.png",
  "summon/Drunken Mist": "cardface/Summon_Diona.png",
  "summon/Sacred Cryo Pearl": "cardface/Summon_IceBall.png",
  "summon/Hydro Samachurl": "cardface/Summon_ShamanWater.png",
  "summon/Hilichurl Berserker": "cardface/Summon_HiliClub.png",
  "summon/Electro Hilichurl Shooter": "cardface/Summon_HiliElectric.png",
  "summon/Cryo Hilichurl Shooter": "cardface/Summon_HiliIce.png",
  "summon/Burning Flame": "cardface/Summon_Ranshaolieyan.png",
  "card/Proliferating Spores": "cardface/Modify_Talent_Fungusgrass.png",
  "card/Beneficent": "cardface/Modify_Constellation_Yaoyao.png",
  "card/The Seed of Stored Knowledge": "cardface/Modify_Constellation_Tighnari.png",
  "card/Keen Sight": "cardface/Modify_Talent_Tighnari.png",
  "card/Floral Sidewinder": "cardface/Modify_Talent_Collei.png",
  "card/Stonehide Reforged": "cardface/Modify_Talent_Rockbrute.png",
  "card/Arataki Ichiban": "cardface/Modify_Talent_Itto.png",
  "card/Descent of Divinity": "cardface/Modify_Constellation_Albedo.png",
  "card/Dominance of Earth": "cardface/Modify_Talent_Zhongli.png",
  "card/I Got Your Back": "cardface/Modify_Constellation_Noel.png",
  "card/Strategic Reserve": "cardface/Modify_Talent_Ningguang.png",
  "card/Transcendent Automaton": "cardface/Modify_Talent_Ningyo.png",
  "card/Gales of Reverie": "cardface/Modify_Talent_Wanderer.png",
  "card/Poetics of Fuubutsu": "cardface/Modify_Talent_Kazuha.png",
  "card/Conqueror of Evil: Guardian Yaksha": "cardface/Modify_Constellation_Xiao.png",
  "card/Embrace of Winds": "cardface/Modify_Talent_Venti.png",
  "card/Lands of Dandelion": "cardface/Modify_Constellation_Qin.png",
  "card/Chaotic Entropy": "cardface/Modify_Constellation_Sucrose.png",
  "card/Lightning Stiletto": "cardface/Summon_Keqing.png",
  "card/Absorbing Prism": "cardface/Modify_Talent_Effigyelectric.png",
  "card/Pulsating Witch": "cardface/Modify_Constellation_Lisa.png",
  "card/The Shrine's Sacred Shade": "cardface/Modify_Talent_Yae.png",
  "card/Wishes Unnumbered": "cardface/Modify_Talent_Shougun.png",
  "card/Sin of Pride": "cardface/Modify_Constellation_Sara.png",
  "card/Lightning Storm": "cardface/Modify_Talent_Beidou.png",
  "card/Featherfall Judgment": "cardface/Modify_Talent_Cyno.png",
  "card/Awakening": "cardface/Modify_Talent_Razor.png",
  "card/Stellar Predator": "cardface/Modify_Talent_Fischl.png",
  "card/Embers Rekindled": "cardface/Modify_Talent_DeaconFire.png",
  "card/Paid in Full": "cardface/Modify_Talent_FatuiPyroAgent.png",
  "card/Stalwart and True": "cardface/Modify_Talent_Dehya.png",
  "card/Right of Final Interpretation": "cardface/Modify_Constellation_Feiyan.png",
  "card/Sanguine Rouge": "cardface/Modify_Talent_Hutao.png",
  "card/Pounding Surprise": "cardface/Modify_Talent_Klee.png",
  "card/Bunny Triggered": "cardface/Modify_Constellation_Ambor.png",
  "card/Grand Expectation": "cardface/Modify_Constellation_Bennett.png",
  "card/Crossfire": "cardface/Modify_Talent_Xiangling.png",
  "card/Flowing Flame": "cardface/Modify_Constellation_Diluc.png",
  "card/Mirror Cage": "cardface/Modify_Talent_Maidenwater.png",
  "card/Streaming Surge": "cardface/Modify_Talent_Chunshui.png",
  "card/The Overflow": "cardface/Modify_Constellation_Candace.png",
  "card/Kyouka Fuushi": "cardface/Modify_Constellation_Ayato.png",
  "card/Tamakushi Casket": "cardface/Modify_Talent_Kokomi.png",
  "card/Abyssal Mayhem: Hydrospout": "cardface/Modify_Constellation_Tartaglia.png",
  "card/Prophecy of Submersion": "cardface/Modify_Constellation_Mona.png",
  "card/The Scent Remained": "cardface/Modify_Constellation_Xingqiu.png",
  "card/Glorious Season": "cardface/Modify_Talent_Barbara.png",
  "card/Cicin's Cold Glare": "cardface/Modify_Talent_MageIce.png",
  "card/Rite of Resurrection": "cardface/Modify_Constellation_Qiqi.png",
  "card/Mystical Abandon": "cardface/Modify_Constellation_Shenhe.png",
  "card/Wellspring of War-Lust": "cardface/Modify_Talent_Eula.png",
  "card/Kanten Senmyou Blessing": "cardface/Modify_Talent_Ayaka.png",
  "card/Steady Breathing": "cardface/Modify_Talent_Chongyun.png",
  "card/Cold-Blooded Strike": "cardface/Modify_Talent_Keaya.png",
  "card/Shaken, Not Purred": "cardface/Modify_Constellation_Diona.png",
  "card/Undivided Heart": "cardface/Modify_Talent_Ganyu.png",
  "card/Butter Crab": "cardface/Event_Food_Huangyou.png",
  "card/Tandoori Roast Chicken": "cardface/Event_Food_Tangduer.png",
  "card/Sashimi Platter": "cardface/Event_Food_Cishen.png",
  "card/Teyvat Fried Egg": "cardface/Event_Food_Jiandan.png",
  "card/Minty Meat Rolls": "cardface/Event_Food_Bohejuan.png",
  "card/Mushroom Pizza": "cardface/Event_Food_Kaomogupisa.png",
  "card/Mondstadt Hash Brown": "cardface/Event_Food_Tudoubin.png",
  "card/Sweet Madame": "cardface/Event_Food_Huaniangji.png",
  "card/Northern Smoked Chicken": "cardface/Event_Food_Beidiyanxunji.png",
  "card/Lotus Flower Crisp": "cardface/Event_Food_Lianhuasu.png",
  "card/Adeptus' Temptation": "cardface/Event_Food_XTQ.png",
  "card/Pankration!": "cardface/Event_Event_Heiquan.png",
  "card/Where Is the Unseen Razor?": "cardface/Event_Event_Cangfen.png",
  "card/Rhythm of the Great Dream": "cardface/Event_Event_Dameng.png",
  "card/Friendship Eternal": "cardface/Event_Event_Yongyuandeyouyi.png",
  "card/The Legend of Vennessa": "cardface/Event_Event_Wennisha.png",
  "card/Heavy Strike": "cardface/Event_Event_Zhonggongji.png",
  "card/Plunging Strike": "cardface/Event_Event_Xialuo.png",
  "card/Guardian's Oath": "cardface/Event_Event_Hufazhishi.png",
  "card/Send Off": "cardface/Event_Event_Songniyicheng.png",
  "card/Quick Knit": "cardface/Event_Event_Kuaikuaifengbushu.png",
  "card/Blessing of the Divine Relic's Installation": "cardface/Event_Event_Shenbaoqiangongzhuci.png",
  "card/Master of Weaponry": "cardface/Event_Event_Zhuwujingtong.png",
  "card/Clax's Arts": "cardface/Event_Event_Baiezhishu.png",
  "card/Starsigns": "cardface/Event_Event_Xingtian.png",
  "card/When the Crane Returned": "cardface/Event_Event_Heguizhishi.png",
  "card/Leave It to Me!": "cardface/Event_Event_Jiaogeiwoba.png",
  "card/I Haven't Lost Yet!": "cardface/Event_Event_Bendayehaimeiyoushu.png",
  "card/Strategize": "cardface/Event_Event_Yunchouweiwo.png",
  "card/Toss-Up": "cardface/Event_Event_Yizhiqiankun.png",
  "card/Changing Shifts": "cardface/Event_Event_Huanbanshijian.png",
  "card/The Bestest Travel Companion!": "cardface/Event_Event_BestAibo.png",
  "card/Fatui Conspiracy": "cardface/Event_Event_Yurenzhongi.png",
  "card/Abyssal Summons": "cardface/Event_Event_Abyssdehuhuan.png",
  "card/Nature and Wisdom": "cardface/Event_Event_Caoyuzhihui.png",
  "card/Stone and Contracts": "cardface/Event_Event_Yanyuqiyue.png",
  "card/Wind and Freedom": "cardface/Event_Event_Fengyuziyou.png",
  "card/Thundering Penance": "cardface/Modify_Talent_Keqing.png",
  "card/Naganohara Meteor Swarm": "cardface/Modify_Constellation_Yoyimiya.png",
  "card/Thunder and Eternity": "cardface/Event_Event_Leiyuyongheng.png",
  "card/Elemental Resonance: Sprawling Greenery": "cardface/Event_ResonanceA_Grass.png",
  "card/Elemental Resonance: Enduring Rock": "cardface/Event_ResonanceA_Rock.png",
  "card/Elemental Resonance: Impetuous Winds": "cardface/Event_ResonanceA_Wind.png",
  "card/Elemental Resonance: High Voltage": "cardface/Event_ResonanceA_Electric.png",
  "card/Elemental Resonance: Fervent Flames": "cardface/Event_ResonanceA_Fire.png",
  "card/Elemental Resonance: Soothing Water": "cardface/Event_ResonanceA_Water.png",
  "card/Elemental Resonance: Shattering Ice": "cardface/Event_ResonanceA_Ice.png",
  "card/Elemental Resonance: Woven Winds": "cardface/Event_ResonanceB_Wind.png",
  "card/Elemental Resonance: Woven Weeds": "cardface/Event_ResonanceB_Grass.png",
  "card/Elemental Resonance: Woven Waters": "cardface/Event_ResonanceB_Water.png",
  "card/Elemental Resonance: Woven Thunder": "cardface/Event_ResonanceB_Electric.png",
  "card/Elemental Resonance: Woven Stone": "cardface/Event_ResonanceB_Rock.png",
  "card/Elemental Resonance: Woven Ice": "cardface/Event_ResonanceB_Ice.png",
  "card/Elemental Resonance: Woven Flames": "cardface/Event_ResonanceB_Fire.png",
  "card/Fresh Wind of Freedom": "cardface/Event_Event_Xinfeng.png",
  "card/Joyous Celebration": "cardface/Event_Event_Qingdian.png",
  "card/Covenant of Rock": "cardface/Event_Event_Chuanglong.png",
  "card/Ancient Courtyard": "cardface/Event_Event_Jiangjun.png",
  "card/Treasure-Seeking Seelie": "cardface/Assist_Prop_Xunbao.png",
  "card/Red Feather Fan": "cardface/Assist_Prop_Hongye.png",
  "card/NRE": "cardface/Assist_Prop_NREMenu.png",
  "card/Yayoi Nanatsuki": "cardface/Assist_NPC_Yayoyi.png",
  "card/Setaria": "cardface/Assist_NPC_Saileita.png",
  "card/Master Zhang": "cardface/Assist_NPC_Laozhang.png",
  "card/Rana": "cardface/Assist_NPC_Lana.png",
  "card/Dunyarzad": "cardface/Assist_NPC_Dina.png",
  "card/Kid Kujirai": "cardface/Assist_NPC_Yingjin.png",
  "card/Hanachirusato": "cardface/Assist_NPC_Huasanli.png",
  "card/Liu Su": "cardface/Assist_NPC_Liusu.png",
  "card/Iron Tongue Tian": "cardface/Assist_NPC_Tiantiezui.png",
  "card/Ellin": "cardface/Assist_NPC_Aileen.png",
  "card/Chang the Ninth": "cardface/Assist_NPC_Changjiuye.png",
  "card/Liben": "cardface/Assist_NPC_LiBen.png",
  "card/Timmie": "cardface/Assist_NPC_Timmy.png",
  "card/Tubby": "cardface/Assist_NPC_AYuan.png",
  "card/Chef Mao": "cardface/Assist_NPC_Maoshifu.png",
  "card/Golden House": "cardface/Assist_Location_Huangjinwu.png",
  "card/Chinju Forest": "cardface/Assist_Location_Zhengshoui.png",
  "card/Vanarana": "cardface/Assist_Location_Hengna.png",
  "card/Sumeru City": "cardface/Assist_Location_Xumi.png",
  "card/Sangonomiya Shrine": "cardface/Assist_Location_Shanhu.png",
  "card/Grand Narukami Shrine": "cardface/Assist_Location_Mingshendashe.png",
  "card/Tenshukaku": "cardface/Assist_Location_Tianshou.png",
  "card/Wangshu Inn": "cardface/Assist_Location_Wangshukezhan.png",
  "card/Dawn Winery": "cardface/Assist_Location_Chenxijiuzhuang.png",
  "card/Jade Chamber": "cardface/Assist_Location_Qunyuge.png",
  "card/Knights of Favonius Library": "cardface/Assist_Location_MdLibrary.png",
  "card/Crimson Witch of Flames": "cardface/Modify_Artifact_Monvtaozhuang.png",
  "card/Heart of Depth": "cardface/Modify_Artifact_Shuitaozhuang.png",
  "card/Viridescent Venerer": "cardface/Modify_Artifact_FengTaozhuang.png",
  "card/Thundering Fury": "cardface/Modify_Artifact_Leitaozhuang.png",
  "card/Archaic Petra": "cardface/Modify_Artifact_YanTaozhuang.png",
  "card/Deepwood Memories": "cardface/Modify_Artifact_CaoTaozhuang.png",
  "card/Blizzard Strayer": "cardface/Modify_Artifact_BinTaozhuang.png",
  "card/Witch's Scorching Hat": "cardface/Modify_Artifact_Monvdanjian.png",
  "card/Wine-Stained Tricorne": "cardface/Modify_Artifact_Shuidanjian.png",
  "card/Viridescent Venerer's Diadem": "cardface/Modify_Artifact_FengDanjian.png",
  "card/Thunder Summoner's Crown": "cardface/Modify_Artifact_Leidanjia.png",
  "card/Mask of Solitude Basalt": "cardface/Modify_Artifact_YanDanjian.png",
  "card/Laurel Coronet": "cardface/Modify_Artifact_CaoDanjian.png",
  "card/Broken Rime's Echo": "cardface/Modify_Artifact_BinDanjian.png",
  "card/Crown of Watatsumi": "cardface/Modify_Artifact_HaiRanDanJian.png",
  "card/Shimenawa's Reminiscence": "cardface/Modify_Artifact_ZhuiyiTaozhuang.png",
  "card/Capricious Visage": "cardface/Modify_Artifact_Zhuiyidanjian.png",
  "card/Vermillion Hereafter": "cardface/Modify_Artifact_ChenshaTaozhuang.png",
  "card/Thundering Poise": "cardface/Modify_Artifact_ChenshaDanjian.png",
  "card/Tenacity of the Millelith": "cardface/Modify_Artifact_QianyanTaozhuang.png",
  "card/General's Ancient Helm": "cardface/Modify_Artifact_Jiangshuai.png",
  "card/Emblem of Severed Fate": "cardface/Modify_Artifact_JueyuanTaozhuang.png",
  "card/Ornate Kabuto": "cardface/Modify_Artifact_Huashi.png",
  "card/Exile's Circlet": "cardface/Modify_Artifact_LiufangzheDanjian.png",
  "card/Instructor's Cap": "cardface/Modify_Artifact_JiaoguanDanjian.png",
  "card/Gambler's Earrings": "cardface/Modify_Artifact_DutuDanjian.png",
  "card/Traveling Doctor's Handkerchief": "cardface/Modify_Artifact_YouyiDanjian.png",
  "card/Lucky Dog's Silver Circlet": "cardface/Modify_Artifact_XingyunerDanjian.png",
  "card/Adventurer's Bandana": "cardface/Modify_Artifact_MaoxianjiaDanjian.png",
  "card/Moonpiercer": "cardface/Modify_Weapon_Guanyue.png",
  "card/King's Squire": "cardface/Modify_Weapon_Wangxia.png",
  "card/Fruit of Fulfillment": "cardface/Modify_Weapon_Arakalari.png",
  "card/Favonius Sword": "cardface/Modify_Weapon_Xifengjian.png",
  "card/Skyward Blade": "cardface/Modify_Weapon_SwordDvalin.png",
  "card/Skyward Spine": "cardface/Modify_Weapon_PoleDvalin.png",
  "card/Skyward Pride": "cardface/Modify_Weapon_ClaymoreDvalin.png",
  "card/Skyward Harp": "cardface/Modify_Weapon_BowDvalin.png",
  "card/Skyward Atlas": "cardface/Modify_Weapon_CatalystDvalin.png",
  "card/Aquila Favonia": "cardface/Modify_Weapon_SwordFalcon.png",
  "card/Engulfing Lightning": "cardface/Modify_Weapon_Narukami.png",
  "card/Vortex Vanquisher": "cardface/Modify_Weapon_Kunwu.png",
  "card/Lithic Spear": "cardface/Modify_Weapon_PoleLapis.png",
  "card/The Bell": "cardface/Modify_Weapon_Troupe.png",
  "card/Wolf's Gravestone": "cardface/Modify_Weapon_ClaymoreWolfmound.png",
  "card/Elegy for the End": "cardface/Modify_Weapon_Widsith.png",
  "card/Amos' Bow": "cardface/Modify_Weapon_Amos.png",
  "card/A Thousand Floating Dreams": "cardface/Modify_Weapon_Ayus.png",
  "card/Sacrificial Bow": "cardface/Modify_Weapon_BowFossil.png",
  "card/Sacrificial Sword": "cardface/Modify_Weapon_SwordFossil.png",
  "card/Sacrificial Greatsword": "cardface/Modify_Weapon_Fossil.png",
  "card/Sacrificial Fragments": "cardface/Modify_Weapon_CatalystFossil.png",
  "card/White Tassel": "cardface/Modify_Weapon_PoleRuby.png",
  "card/White Iron Greatsword": "cardface/Modify_Weapon_ClaymoreTin.png",
  "card/Traveler's Handy Sword": "cardface/Modify_Weapon_SwordDarker.png",
  "card/Raven Bow": "cardface/Modify_Weapon_BowCrowfeather.png",
  "card/Magic Guide": "cardface/Modify_Weapon_CatalystIntro.png",
  "summon/Dandelion Field": "cardface/Summon_DandelionBreeze.png",
  "summon/Large Wind Spirit": "cardface/Summon_LargeWindSpirit.png",
  "summon/Guoba": "cardface/Summon_Guoba.png",
  "summon/Oceanic Mimic: Raptor": "cardface/Summon_Raptor.png",
  "summon/Talisman Spirit": "cardface/Summon_Shenhe.png",
  "card/Jueyun Guoba": "cardface/Event_Food_Jueyunguoba.png",
  "card/Parametric Transformer": "cardface/Assist_Prop_ParametricTransformer.png",
  "card/Xudong": "cardface/Assist_NPC_Xudong.png",
  "card/Wagner": "cardface/Assist_NPC_Wagner.png",
  "card/Timaeus": "cardface/Assist_NPC_Timaeus.png",
  "card/Katheryne": "cardface/Assist_NPC_Katheryne.png",
  "card/Paimon": "cardface/Assist_NPC_Paimon.png",
  "card/Gandharva Ville": "cardface/Assist_Location_Gandharva.png",
  "card/Favonius Cathedral": "cardface/Assist_Location_FavoniusChurch.png",
  "card/Liyue Harbor Wharf": "cardface/Assist_Location_LiyueHarbor.png",
  "team_status/Fatui Ambusher: Electrohammer Vanguard": "status/Event_Fatui_Elec.png",
  "team_status/Fatui Ambusher: Pyroslinger Bracer": "status/Event_Fatui_Fire.png",
  "team_status/Fatui Ambusher: Mirror Maiden": "status/Event_Fatui_Water.png",
  "team_status/Fatui Ambusher: Cryo Cicin Mage": "status/Event_Fatui_Ice.png",
  "team_status/Thunderbeast's Targe": "status/Beidou_E.png",
  "team_status/Tenko Thunderbolts": "status/Yae_E.png",
  "team_status/Fortune-Preserving Talisman": "status/Qiqi_E.png",
  "team_status/Icicle": "status/Kaeya_E.png",
  "team_status/Pyronado": "status/Xiangling_E.png",
  "team_status/Aurous Blaze": "status/Yoimiya_E.png",
  "team_status/Inspiration Field": "status/Bennett_E.png",
  "team_status/Sparks 'n' Splash": "status/Klee_E.png",
  "team_status/Adeptal Legacy": "status/Yaoyao_E.png",
  "team_status/Shrine of Maya": "status/Nahida_E.png",
  "team_status/Prayer of the Crimson Crown": "status/Candace_E.png",
  "team_status/Rainbow Bladework": "status/Xingqiu_E.png",
  "team_status/Illusory Bubble": "status/Mona_E.png",
  "team_status/Dendro Core": "status/Reaction_116.png",
  "team_status/Catalyzing Field": "status/Reaction_117.png",
  "charactor_status/Ceremonial Garment": "status/Kokomi_E.png",
  "charactor_status/Melee Stance": "status/Tartaglia_S_01.png",
  "charactor_status/Ranged Stance": "status/Tartaglia_S_02.png",
  "charactor_status/Riptide": "status/Tartaglia_S_03.png",
  "charactor_status/Yaksha's Mask": "status/Xiao_E.png",
  "charactor_status/Pactsworn Pathclearer": "status/Cyno_E.png",
  "charactor_status/The Wolf Within": "status/Razor_E.png",
  "charactor_status/Chakra Desiderata": "status/Shougun_E.png",
  "charactor_status/Petrification": "status/Zhongli_E.png",
  "charactor_status/Raging Oni King": "status/Itto_E.png",
  "charactor_status/Sweeping Time": "status/Noel_E.png",
  "charactor_status/Radical Vitality": "status/FungusRaptor_S.png",
  "charactor_status/Seed of Skandha": "status/Nahida_S.png",
  "charactor_status/Brilliance": "status/Feiyan_E.png",
  "element/PYRO": "status/Common_Element_Fire.png",
  "element/HYDRO": "status/Common_Element_Water.png",
  "element/CRYO": "status/Common_Element_Ice.png",
  "element/ELECTRO": "status/Common_Element_Electric.png",
  "element/ANEMO": "status/Common_Element_Wind.png",
  "element/GEO": "status/Common_Element_Rock.png",
  "element/DENDRO": "status/Common_Element_Grass.png",
  "element/PHYSICAL": "status/Common_Element_Physics.png",
  "element/HEAL": "status/Common_Element_Heal.png",
  "dice/PYRO": "dice/Fire.png",
  "dice/HYDRO": "dice/Water.png",
  "dice/CRYO": "dice/Frost.png",
  "dice/ELECTRO": "dice/Elect.png",
  "dice/ANEMO": "dice/Wind.png",
  "dice/GEO": "dice/Roach.png",
  "dice/DENDRO": "dice/Grass.png",
  "dice/OMNI": "dice/Any.png",
  "dice/CHARGE": "dice/Energy.png",
  "dice/MATCHING": "dice/Same.png",
  "dice/UNALIGNED": "dice/Diff.png",
  "dice/ARCANE_FULL": "dice/Legend.png",
  "dice/ARCANE_EMPTY": "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
  "icon/BARRIER": "mark/Barrier.png",
  "icon/SHIELD": "mark/Shield.png",
  "icon/COUNTER": "mark/Counter.png",
  "icon/TIMESTATE": "mark/TimeState.png",
}

export default nameMap;
