name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: |
          yarn build
          sed -i 's/href="\//href="/g' dist/index.html
          sed -i 's/src="\//src="/g' dist/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/

      - name: Deploy to GitHub Pages
        if: github.event_name != 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: gh-pages
